### ISSUE TITLE
Correct home page for VICE

### ISSUE THREAD

**Issue by Rhialto** [markusC64/nibtools#11]
The page http://viceteam.org/ in readme.txt is outdated. Can you correct it to the latest version? https://vice-emu.sourceforge.io/ would be nice.

**Comment by markusC64** [comment]
Fixed. In general, this version is out of support and only pull requests are accepted.

The added functionality is available in g64conv, too.

**Comment by Rhialto** [comment]
Thanks. But I was looking for `nibconv` because I found a bunch of `.nib` files. I had to convert them to `.g64` so I could use them with VICE.

**Comment by markusC64** [comment]
In that case using the original nibconv from nibtools might be an option that I am using, too.
